namespace GLSLX.Tests {
  def testEmitter {

# Test symbol modifier pass-through
test("
void main(in int i, out int o, inout int io, const int ci) {
  lowp float l;
  mediump float m;
  highp float h;
  const float cf = 0.0;
}
", "
void main(in int i, out int o, inout int io, const int ci) {
  lowp float l;
  mediump float m;
  highp float h;
  const float cf = 0.0;
}
")

# Test array type pass-through
test("
void main() {
  int x[2], y[3];
  x[0] = y[1];
}
", "
void main() {
  int x[2], y[3];
  x[0] = y[1];
}
")

  }
}
