namespace GLSLX.Tests {
  def testParser {

# Test comment parsing
test("
// this is a comment
varying vec2 v2;
/*
this is a multi-
line comment
*/
void main() {
  gl_FragColor.xy = v2;
}
", "
varying vec2 v2;

void main() {
  gl_FragColor.xy = v2;
}
")

# Test comment parsing
test("
// this is a comment\r
varying vec2 v2;\r
/*\r
this is a multi-\r
line comment\r
*/\r
void main() {\r
  gl_FragColor.xy = v2;\r
}\r
", "
varying vec2 v2;

void main() {
  gl_FragColor.xy = v2;
}
")

# Test qualifier parsing for arguments
test("
void main(
  attribute float a,
  const float c,
  highp float h,
  in float i,
  inout float io,
  lowp float l,
  mediump float m,
  out float o,
  uniform float u,
  varying float v
) {
}
", "
<stdin>:2:3: error: Cannot use this qualifier here
  attribute float a,
  ~~~~~~~~~
<stdin>:10:3: error: Cannot use this qualifier here
  uniform float u,
  ~~~~~~~
<stdin>:11:3: error: Cannot use this qualifier here
  varying float v
  ~~~~~~~
")

  }
}
