namespace GLSLX.Parser {
  def typeParselet(pratt Pratt, kind TokenKind) {
    pratt.parselet(kind, .LOWEST).prefix = context => parseType(context, .REPORT_ERRORS)
  }

  def unaryPrefix(kind NodeKind) fn(ParserContext, Token, Node) Node {
    assert(kind.isUnaryPrefix)
    return (context, token, value) => Node.createUnary(kind, value).withRange(Range.span(token.range, value.range)).withInternalRange(token.range)
  }

  def unaryPostfix(kind NodeKind) fn(ParserContext, Node, Token) Node {
    assert(kind.isUnaryPostfix)
    return (context, value, token) => Node.createUnary(kind, value).withRange(Range.span(value.range, token.range)).withInternalRange(token.range)
  }

  def binaryParselet(kind NodeKind) fn(ParserContext, Node, Token, Node) Node {
    assert(kind.isBinary)
    return (context, left, token, right) => Node.createBinary(kind, left, right).withRange(Range.span(left.range, right.range)).withInternalRange(token.range)
  }

  def parseInt(text string) int {
    var n = text.count
    var c = text[n - 1]
    if c == 'u' || c == 'U' {
      text = text.slice(0, n - 1)
    }
    if text.count > 1 && text[0] == '0' && (text[1] != 'x' && text[1] != 'X') {
      return dynamic.parseInt(text, 8)
    }
    return (text as dynamic) | 0
  }

  def parseFloat(text string) double {
    return +(text as dynamic)
  }

  var pratt100 Pratt = null
  var pratt300 Pratt = null

  def createExpressionParser(version Version) Pratt {
    const version300 = version == .ES_300
    if version300 {
      if pratt300 != null { return pratt300 }
    } else {
      if pratt100 != null { return pratt100 }
    }

    var pratt = Pratt.new

    var invalidUnaryOperator = (context ParserContext, token Token, value Node) Node => {
      context.log.syntaxErrorInvalidOperator(token.range)
      return Node.createUnknownConstant(.ERROR).withRange(Range.span(token.range, value.range))
    }

    var invalidBinaryOperator = (context ParserContext, left Node, token Token, right Node) Node => {
      context.log.syntaxErrorInvalidOperator(token.range)
      return Node.createUnknownConstant(.ERROR).withRange(Range.span(left.range, right.range))
    }

    pratt.literal(.TRUE, (context, token) => Node.createBool(true).withRange(token.range))
    pratt.literal(.FALSE, (context, token) => Node.createBool(false).withRange(token.range))
    pratt.literal(.INT_LITERAL, (context, token) => Node.createInt(parseInt(token.range.toString)).withRange(token.range))
    pratt.literal(.FLOAT_LITERAL, (context, token) => Node.createFloat(parseFloat(token.range.toString)).withRange(token.range))

    pratt.literal(.UINT_LITERAL, (context, token) => {
      if !version300 {
        context.log.syntaxErrorUnexpectedToken(token)
        return Node.createParseError.withRange(token.range)
      }
      return Node.createUint(parseInt(token.range.toString)).withRange(token.range)
    })

    typeParselet(pratt, .BOOL)
    typeParselet(pratt, .BVEC2)
    typeParselet(pratt, .BVEC3)
    typeParselet(pratt, .BVEC4)
    typeParselet(pratt, .FLOAT)
    typeParselet(pratt, .INT)
    typeParselet(pratt, .IVEC2)
    typeParselet(pratt, .IVEC3)
    typeParselet(pratt, .IVEC4)
    typeParselet(pratt, .MAT2)
    typeParselet(pratt, .MAT3)
    typeParselet(pratt, .MAT4)
    typeParselet(pratt, .VEC2)
    typeParselet(pratt, .VEC3)
    typeParselet(pratt, .VEC4)
    typeParselet(pratt, .VOID)

    typeParselet(pratt, .MAT2X3)
    typeParselet(pratt, .MAT2X4)
    typeParselet(pratt, .MAT3X2)
    typeParselet(pratt, .MAT3X4)
    typeParselet(pratt, .MAT4X2)
    typeParselet(pratt, .MAT4X3)
    typeParselet(pratt, .UINT)
    typeParselet(pratt, .UVEC2)
    typeParselet(pratt, .UVEC3)
    typeParselet(pratt, .UVEC4)

    pratt.prefix(.COMPLEMENT, .UNARY_PREFIX, version300 ? unaryPrefix(.COMPLEMENT) : invalidUnaryOperator)
    pratt.prefix(.DECREMENT, .UNARY_PREFIX, unaryPrefix(.PREFIX_DECREMENT))
    pratt.prefix(.INCREMENT, .UNARY_PREFIX, unaryPrefix(.PREFIX_INCREMENT))
    pratt.prefix(.MINUS, .UNARY_PREFIX, unaryPrefix(.NEGATIVE))
    pratt.prefix(.NOT, .UNARY_PREFIX, unaryPrefix(.NOT))
    pratt.prefix(.PLUS, .UNARY_PREFIX, unaryPrefix(.POSITIVE))

    pratt.postfix(.DECREMENT, .UNARY_POSTFIX, unaryPostfix(.POSTFIX_DECREMENT))
    pratt.postfix(.INCREMENT, .UNARY_POSTFIX, unaryPostfix(.POSTFIX_INCREMENT))

    pratt.infix(.DIVIDE, .MULTIPLY, binaryParselet(.DIVIDE))
    pratt.infix(.EQUAL, .COMPARE, binaryParselet(.EQUAL))
    pratt.infix(.GREATER_THAN, .COMPARE, binaryParselet(.GREATER_THAN))
    pratt.infix(.GREATER_THAN_OR_EQUAL, .COMPARE, binaryParselet(.GREATER_THAN_OR_EQUAL))
    pratt.infix(.LESS_THAN, .COMPARE, binaryParselet(.LESS_THAN))
    pratt.infix(.LESS_THAN_OR_EQUAL, .COMPARE, binaryParselet(.LESS_THAN_OR_EQUAL))
    pratt.infix(.MINUS, .ADD, binaryParselet(.SUBTRACT))
    pratt.infix(.MULTIPLY, .MULTIPLY, binaryParselet(.MULTIPLY))
    pratt.infix(.NOT_EQUAL, .COMPARE, binaryParselet(.NOT_EQUAL))
    pratt.infix(.PLUS, .ADD, binaryParselet(.ADD))
    pratt.infix(.REMAINDER, .MULTIPLY, version300 ? binaryParselet(.REMAINDER) : invalidBinaryOperator)
    pratt.infix(.SHIFT_LEFT, .SHIFT, version300 ? binaryParselet(.SHIFT_LEFT) : invalidBinaryOperator)
    pratt.infix(.SHIFT_RIGHT, .SHIFT, version300 ? binaryParselet(.SHIFT_RIGHT) : invalidBinaryOperator)
    pratt.infix(.LOGICAL_OR, .LOGICAL_OR, binaryParselet(.LOGICAL_OR))
    pratt.infix(.LOGICAL_XOR, .LOGICAL_XOR, binaryParselet(.LOGICAL_XOR))
    pratt.infix(.LOGICAL_AND, .LOGICAL_AND, binaryParselet(.LOGICAL_AND))
    pratt.infix(.BITWISE_AND, .BITWISE_AND, version300 ? binaryParselet(.BITWISE_AND) : invalidBinaryOperator)
    pratt.infix(.BITWISE_OR, .BITWISE_OR, version300 ? binaryParselet(.BITWISE_OR) : invalidBinaryOperator)
    pratt.infix(.BITWISE_XOR, .BITWISE_XOR, version300 ? binaryParselet(.BITWISE_XOR) : invalidBinaryOperator)

    pratt.infixRight(.ASSIGN, .ASSIGN, binaryParselet(.ASSIGN))
    pratt.infixRight(.ASSIGN_ADD, .ASSIGN, binaryParselet(.ASSIGN_ADD))
    pratt.infixRight(.ASSIGN_BITWISE_AND, .ASSIGN, version300 ? binaryParselet(.ASSIGN_BITWISE_AND) : invalidBinaryOperator)
    pratt.infixRight(.ASSIGN_BITWISE_OR, .ASSIGN, version300 ? binaryParselet(.ASSIGN_BITWISE_OR) : invalidBinaryOperator)
    pratt.infixRight(.ASSIGN_BITWISE_XOR, .ASSIGN, version300 ? binaryParselet(.ASSIGN_BITWISE_XOR) : invalidBinaryOperator)
    pratt.infixRight(.ASSIGN_DIVIDE, .ASSIGN, binaryParselet(.ASSIGN_DIVIDE))
    pratt.infixRight(.ASSIGN_MULTIPLY, .ASSIGN, binaryParselet(.ASSIGN_MULTIPLY))
    pratt.infixRight(.ASSIGN_REMAINDER, .ASSIGN, version300 ? binaryParselet(.ASSIGN_REMAINDER) : invalidBinaryOperator)
    pratt.infixRight(.ASSIGN_SHIFT_LEFT, .ASSIGN, version300 ? binaryParselet(.ASSIGN_SHIFT_LEFT) : invalidBinaryOperator)
    pratt.infixRight(.ASSIGN_SHIFT_RIGHT, .ASSIGN, version300 ? binaryParselet(.ASSIGN_SHIFT_RIGHT) : invalidBinaryOperator)
    pratt.infixRight(.ASSIGN_SUBTRACT, .ASSIGN, binaryParselet(.ASSIGN_SUBTRACT))

    # Name
    pratt.parselet(.IDENTIFIER, .LOWEST).prefix = context => {
      var type = parseType(context, .IGNORE_ERRORS)
      if type != null {
        return type
      }

      var token = context.next
      var name = token.range.toString
      var symbol = context.scope.find(name)
      if symbol == null {
        context.log.syntaxErrorBadSymbolReference(token.range)
        return Node.createParseError.withRange(token.range)
      }

      # Check extension usage
      if symbol.requiredExtension != null && context.compilationData.extensionBehavior(symbol.requiredExtension) == .DISABLE {
        context.log.syntaxErrorDisabledExtension(token.range, name, symbol.requiredExtension)
      }

      symbol.useCount++
      return Node.createName(symbol).withRange(token.range)
    }

    # Sequence
    pratt.infix(.COMMA, .COMMA, (context, left, token, right) => {
      if left.kind != .SEQUENCE {
        left = Node.createSequence.appendChild(left).withRange(left.range)
      }
      left.appendChild(right)
      return left.withRange(context.spanSince(left.range))
    })

    # Dot
    pratt.parselet(.DOT, .MEMBER).infix = (context, left) => {
      var dot = context.current.range
      context.next
      var name = context.current.range
      if !context.expect(.IDENTIFIER) {
        return Node.createDot(left, "").withRange(context.spanSince(left.range)).withInternalRange(dot.rangeAtEnd)
      }
      return Node.createDot(left, name.toString).withRange(context.spanSince(left.range)).withInternalRange(name)
    }

    # Group
    pratt.parselet(.LEFT_PARENTHESIS, .LOWEST).prefix = (context) => {
      var token = context.next
      var value = context.pratt.parse(context, .LOWEST)
      if value == null || !context.expect(.RIGHT_PARENTHESIS) {
        return Node.createParseError.withRange(context.spanSince(token.range))
      }
      return value.withRange(context.spanSince(token.range))
    }

    # Call
    pratt.parselet(.LEFT_PARENTHESIS, .UNARY_POSTFIX).infix = (context, left) => {
      var token = context.next
      var node = Node.createCall(left)
      if !parseCommaSeparatedList(context, node, .RIGHT_PARENTHESIS) {
        return Node.createParseError.withRange(context.spanSince(token.range))
      }

      # Automatically fill in the omitted array size for array constructors
      if left.kind == .TYPE && left.resolvedType.isArrayOf != null && left.typeArraySize.isEmptySequence {
        left.resolvedType = left.resolvedType.isArrayOf.arrayType(node.childCount - 1)
      }

      return node.withRange(context.spanSince(left.range)).withInternalRange(context.spanSince(token.range))
    }

    # Index
    pratt.parselet(.LEFT_BRACKET, .MEMBER).infix = (context, left) => {
      var token = context.next

      # The "[]" syntax isn't valid but skip over it and recover
      if context.peek(.RIGHT_BRACKET) {
        context.unexpectedToken
        context.next
        return Node.createParseError.withRange(context.spanSince(token.range))
      }

      var value = context.pratt.parse(context, .LOWEST)
      if value == null || !context.expect(.RIGHT_BRACKET) {
        return Node.createParseError.withRange(context.spanSince(token.range))
      }
      return Node.createBinary(.INDEX, left, value).withRange(context.spanSince(left.range)).withInternalRange(context.spanSince(token.range))
    }

    # Hook
    pratt.parselet(.QUESTION, .ASSIGN).infix = (context, left) => {
      var token = context.next
      var middle = context.pratt.parse(context, .COMMA)
      if middle == null || !context.expect(.COLON) {
        return Node.createParseError.withRange(context.spanSince(token.range))
      }
      var right = context.pratt.parse(context, .COMMA)
      if right == null {
        return Node.createParseError.withRange(context.spanSince(token.range))
      }
      return Node.createHook(left, middle, right).withRange(context.spanSince(left.range))
    }

    if version300 {
      pratt300 = pratt
    } else {
      pratt100 = pratt
    }
    return pratt
  }

  def parseCommaSeparatedList(context ParserContext, parent Node, stop TokenKind) bool {
    var isFirst = true
    while !context.eat(stop) {
      if !isFirst  {
        context.expect(.COMMA)
      }
      var firstToken = context.current
      var value = context.pratt.parse(context, .COMMA)
      if value != null {
        parent.appendChild(value)
      } else {
        # Recover from errors due to partially-typed calls
        parent.appendChild(Node.createParseError.withRange(context.spanSince(firstToken.range)))
        if !context.peek(.COMMA) && !context.peek(stop) {
          return false
        }
      }
      isFirst = false
    }
    return true
  }

  def parseDoWhile(context ParserContext) Node {
    var token = context.next
    context.pushScope(Scope.new(.LOOP, context.scope))
    var body = parseStatement(context, .LOCAL)
    if body == null || !context.expect(.WHILE) || !context.expect(.LEFT_PARENTHESIS) {
      return null
    }
    var test = context.pratt.parse(context, .LOWEST)
    if test == null {
      return null
    }
    if !context.expect(.RIGHT_PARENTHESIS) {
      return null
    }
    context.popScope
    return checkForSemicolon(context, token.range, Node.createDoWhile(body, test))
  }

  def parseExportOrImport(context ParserContext) Node {
    var token = context.next
    var old = context.flags
    context.flags |=
      token.kind == .EXPORT_VERTEX ? .EXPORTED_VERTEX :
      token.kind == .EXPORT_FRAGMENT ? .EXPORTED_FRAGMENT :
      token.kind == .EXPORT ? .EXPORTED_VERTEX | .EXPORTED_FRAGMENT :
      .IMPORTED

    # Parse a modifier block
    if context.eat(.LEFT_BRACE) {
      var node = Node.createModifierBlock
      if !parseStatements(context, node, .GLOBAL) || !context.expect(.RIGHT_BRACE) {
        context.flags = old
        return null
      }
      context.flags = old
      return node.withRange(context.spanSince(token.range))
    }

    # Just parse a single statement
    var statement = parseStatement(context, .GLOBAL)
    if statement == null {
      context.flags = old
      return null
    }
    context.flags = old
    return statement
  }

  const _extensionBehaviors StringMap<ExtensionBehavior> = {
    "disable": .DISABLE,
    "enable": .ENABLE,
    "require": .REQUIRE,
    "warn": .WARN,
  }

  # From https://www.khronos.org/registry/webgl/extensions/
  const _knownWebGLExtensions StringMap<int> = {
    "GL_OES_standard_derivatives": 0,
    "GL_EXT_frag_depth": 0,
    "GL_EXT_draw_buffers": 0,
    "GL_EXT_shader_texture_lod": 0,
  }

  def parseExtension(context ParserContext) Node {
    var token = context.next
    var range = context.current.range
    if !context.expect(.IDENTIFIER) {
      return null
    }
    var name = range.toString

    # Parse an extension block (a non-standard addition)
    if context.eat(.LEFT_BRACE) {
      if !(name in context.compilationData.currentExtensions) {
        context.compilationData.currentExtensions[name] = .DEFAULT # Silence warnings about this name
      }
      var block = Node.createModifierBlock
      if !parseStatements(context, block, .GLOBAL) || !context.expect(.RIGHT_BRACE) {
        return null
      }
      for child = block.firstChild; child != null; child = child.nextSibling {
        if child.kind == .VARIABLES {
          for variable = child.variablesType.nextSibling; variable != null; variable = variable.nextSibling {
            variable.symbol.requiredExtension = name
          }
        } else if child.symbol != null {
          child.symbol.requiredExtension = name
        }
      }
      return block.withRange(context.spanSince(token.range))
    }

    # Warn about typos
    if !(name in _knownWebGLExtensions) && !(name in context.compilationData.currentExtensions) {
      context.log.syntaxWarningUnknownExtension(range, name)
    }

    # Parse a regular extension pragma
    if !context.expect(.COLON) {
      return null
    }
    var text = context.current.range.toString
    if !(text in _extensionBehaviors) {
      context.unexpectedToken
      return null
    }
    context.next

    # Activate or deactivate the extension
    var behavior = _extensionBehaviors[text]
    context.compilationData.currentExtensions[name] = behavior
    return Node.createExtension(name, behavior).withRange(context.spanSince(token.range)).withInternalRange(range)
  }

  def parseFor(context ParserContext) Node {
    var token = context.next
    context.pushScope(Scope.new(.LOOP, context.scope))
    if !context.expect(.LEFT_PARENTHESIS) {
      return null
    }

    # Setup
    var setup Node = null
    if !context.eat(.SEMICOLON) {
      # Check for a type
      var comments = parseLeadingComments(context)
      var flags = parseFlags(context, .LOCAL)
      var type Node = null
      if flags != 0 {
        type = parseType(context, .REPORT_ERRORS)
        if type == null {
          return null
        }
      } else {
        type = parseType(context, .IGNORE_ERRORS)
      }

      # Try to parse a variable
      if type != null {
        setup = parseAfterType(context, token.range, flags, type, .AVOID_FUNCTIONS, comments)
        if setup == null {
          return null
        }
      } else {
        setup = context.pratt.parse(context, .LOWEST)
        if setup == null {
          return null
        }
        if !context.expect(.SEMICOLON) {
          return null
        }
      }
    }

    # Test
    var test Node = null
    if !context.eat(.SEMICOLON) {
      test = context.pratt.parse(context, .LOWEST)
      if test == null {
        return null
      }
      if !context.expect(.SEMICOLON) {
        return null
      }
    }

    # Update
    var update Node = null
    if !context.eat(.RIGHT_PARENTHESIS) {
      update = context.pratt.parse(context, .LOWEST)
      if update == null {
        return null
      }
      if !context.expect(.RIGHT_PARENTHESIS) {
        return null
      }
    }

    # Body
    var body = parseStatement(context, .LOCAL)
    if body == null {
      return null
    }
    context.popScope
    return Node.createFor(setup, test, update, body).withRange(context.spanSince(token.range))
  }

  def parseIf(context ParserContext) Node {
    var token = context.next
    if !context.expect(.LEFT_PARENTHESIS) {
      return null
    }
    var firstToken = context.current
    var test = context.pratt.parse(context, .LOWEST)
    if test == null {
      test = Node.createParseError.withRange(context.spanSince(firstToken.range))
    }
    if !context.expect(.RIGHT_PARENTHESIS) {
      return null
    }
    var yes = parseStatement(context, .LOCAL)
    if yes == null {
      return null
    }
    var no Node = null
    if context.eat(.ELSE) {
      no = parseStatement(context, .LOCAL)
      if no == null {
        return null
      }
    }
    return Node.createIf(test, yes, no).withRange(context.spanSince(token.range))
  }

  def parseVersion(context ParserContext) Node {
    if !context.isFirstToken {
      context.log.syntaxErrorUnexpectedVersion(context.current.range)
    }

    var token = context.next
    var range = context.current.range
    if !context.expect(.INT_LITERAL) {
      return null
    }

    # GLSL ES 1.00
    if range.toString == "100" {
      return Node.createVersion("100").withRange(context.spanSince(token.range))
    }

    # GLSL ES 1.00
    if range.toString == "300" {
      var ident = context.current.range
      if !context.expect(.IDENTIFIER) {
        return null
      }
      if ident.toString == "es" {
        return Node.createVersion("300 es").withRange(context.spanSince(token.range))
      }
    }

    context.log.syntaxErrorUnrecognizedVersion(range)
    return Node.createVersion(context.spanSince(range).toString).withRange(context.spanSince(token.range))
  }

  def parseWhile(context ParserContext) Node {
    var token = context.next
    context.pushScope(Scope.new(.LOOP, context.scope))
    if !context.expect(.LEFT_PARENTHESIS) {
      return null
    }
    var firstToken = context.current
    var test = context.pratt.parse(context, .LOWEST)
    if test == null {
      test = Node.createParseError.withRange(context.spanSince(firstToken.range))
    }
    if !context.expect(.RIGHT_PARENTHESIS) {
      return null
    }
    var body = parseStatement(context, .LOCAL)
    if body == null {
      return null
    }
    context.popScope
    return Node.createWhile(test, body).withRange(context.spanSince(token.range))
  }

  def parseReturn(context ParserContext) Node {
    var token = context.next
    var value Node = null
    if !context.eat(.SEMICOLON) {
      var firstToken = context.current
      value = context.pratt.parse(context, .LOWEST)
      if value == null {
        value = Node.createParseError.withRange(context.spanSince(firstToken.range))
      }
      context.expect(.SEMICOLON)
    }
    return Node.createReturn(value).withRange(context.spanSince(token.range))
  }

  def parsePrecision(context ParserContext) Node {
    var token = context.next
    var flag SymbolFlags = 0
    switch context.current.kind {
      case .LOWP { flag = .LOWP }
      case .MEDIUMP { flag = .MEDIUMP }
      case .HIGHP { flag = .HIGHP }
      default {
        context.unexpectedToken
        return null
      }
    }
    context.next
    var type = parseType(context, .REPORT_ERRORS)
    if type == null {
      return null
    }
    return checkForSemicolon(context, token.range, Node.createPrecision(flag, type))
  }

  def parseStruct(context ParserContext, flags int, comments List<string>) Node {
    var name = context.current.range
    if !context.expect(.IDENTIFIER) {
      return null
    }

    var symbol = StructSymbol.new(context.compilationData.nextSymbolID, name, name.toString, Scope.new(.STRUCT, context.scope))
    symbol.flags |= context.flags | flags
    symbol.comments = comments
    if !tryToDefineUniquelyInScope(context, symbol) {
      return null
    }

    var range = context.current.range
    var block = Node.createStructBlock
    var variables Node = null

    if !context.expect(.LEFT_BRACE) {
      return null
    }

    context.pushScope(symbol.scope)
    while !context.peek(.RIGHT_BRACE) && !context.peek(.END_OF_FILE) {
      var statement = parseStatement(context, .STRUCT)
      if statement == null {
        return null
      }

      if statement.kind != .VARIABLES {
        context.log.syntaxErrorInsideStruct(statement.range)
        continue
      }

      block.appendChild(statement)

      for child = statement.variablesType.nextSibling; child != null; child = child.nextSibling {
        var variable = child.symbol.asVariable
        symbol.variables.append(variable)

        if variable.value != null {
          context.log.syntaxErrorStructVariableInitializer(variable.value.range)
        }
      }
    }
    context.popScope

    if !context.expect(.RIGHT_BRACE) {
      return null
    }

    block.withRange(context.spanSince(range))

    # Parse weird struct-variable hybrid things
    #
    #   struct S { int x; } y, z[2];
    #
    if context.peek(.IDENTIFIER) {
      variables = parseVariables(0, Node.createType(symbol.resolvedType), context.next.range, context, comments)
      if variables == null {
        return null
      }
    }

    else {
      context.expect(.SEMICOLON)
    }

    return Node.createStruct(symbol, block, variables)
  }

  def checkForLoopAndSemicolon(context ParserContext, range Range, node Node) Node {
    var found = false
    for scope = context.scope; scope != null; scope = scope.parent {
      if scope.kind == .LOOP {
        found = true
        break
      }
    }
    if !found {
      context.log.syntaxErrorOutsideLoop(range)
    }
    return checkForSemicolon(context, range, node)
  }

  def checkForSemicolon(context ParserContext, range Range, node Node) Node {
    context.expect(.SEMICOLON)
    return node.withRange(context.spanSince(range))
  }

  enum Allow {
    AVOID_FUNCTIONS
    ALLOW_FUNCTIONS
  }

  def parseAfterType(context ParserContext, range Range, flags SymbolFlags, type Node, allow Allow, comments List<string>) Node {
    var name = context.current.range
    if flags == 0 && !context.peek(.IDENTIFIER) {
      var value = context.pratt.resume(context, .LOWEST, type)
      if value == null {
        return null
      }
      return checkForSemicolon(context, range, Node.createExpression(value))
    }
    if !context.expect(.IDENTIFIER) {
      return null
    }
    if context.eat(.LEFT_PARENTHESIS) {
      return parseFunction(flags, type, name, context, comments)
    }
    var variables = parseVariables(flags, type, name, context, comments)
    if variables == null {
      return null
    }
    return variables.withRange(context.spanSince(range))
  }

  def parseLeadingComments(context ParserContext) List<string> {
    var firstToken = context.current
    var comments = firstToken.comments
    if comments == null {
      return null
    }

    var nextRangeStart = firstToken.range.start
    var leadingComments List<string> = null

    # Scan the comments backwards
    for i = comments.count - 1; i >= 0; i-- {
      var comment = comments[i]

      # Count the newlines in between this token and the next token
      var whitespace = comment.source.contents.slice(comment.end, nextRangeStart)
      var newlineCount = 0
      for j = 0; j < whitespace.count; j++ {
        var c = whitespace[j]
        if c == '\r' || c == '\n' {
          newlineCount++
          if c == '\r' && j + 1 < whitespace.count && whitespace[j + 1] == '\n' {
            j++
          }
        }
      }

      # Don't count comments if there's a blank line in between the comment and the statement
      if newlineCount > 1 {
        break
      }

      # Otherwise, count this comment
      (leadingComments ?= []).append(comment.toString)
      nextRangeStart = comment.start
    }

    if leadingComments != null {
      leadingComments.reverse
    }
    return leadingComments
  }

  def parseStatement(context ParserContext, mode VariableKind) Node {
    var token = context.current

    switch token.kind {
      case .BREAK { return checkForLoopAndSemicolon(context, context.next.range, Node.createBreak) }
      case .CONTINUE { return checkForLoopAndSemicolon(context, context.next.range, Node.createContinue) }
      case .DISCARD { return checkForSemicolon(context, context.next.range, Node.createDiscard) }
      case .DO { return parseDoWhile(context) }
      case .EXPORT, .EXPORT_FRAGMENT, .EXPORT_VERTEX, .IMPORT { return parseExportOrImport(context) }
      case .EXTENSION { return parseExtension(context) }
      case .FOR { return parseFor(context) }
      case .IF { return parseIf(context) }
      case .LEFT_BRACE { return parseBlock(context) }
      case .PRECISION { return parsePrecision(context) }
      case .RETURN { return parseReturn(context) }
      case .SEMICOLON { return Node.createBlock.withRange(context.next.range) }
      case .VERSION { return parseVersion(context) }
      case .WHILE { return parseWhile(context) }
    }

    # Try to parse a variable or function
    var comments = parseLeadingComments(context)
    var flags = parseFlags(context, mode)
    var type Node = null
    if context.eat(.STRUCT) {
      var struct = parseStruct(context, flags, comments)
      if struct == null {
        return null
      }
      return struct.withRange(context.spanSince(token.range))
    }
    if flags != 0 {
      type = parseType(context, .REPORT_ERRORS)
      if type == null {
        return null
      }
    } else {
      type = parseType(context, .IGNORE_ERRORS)
    }
    if type != null {
      return parseAfterType(context, token.range, flags, type, .ALLOW_FUNCTIONS, comments)
    }

    # Parse an expression
    var value = context.pratt.parse(context, .LOWEST)
    if value == null {
      return null
    }
    return checkForSemicolon(context, token.range, Node.createExpression(value))
  }

  def checkStatementLocation(context ParserContext, node Node) {
    if node.kind == .VARIABLES || node.kind == .STRUCT {
      return
    }

    var isOutsideFunction =
      context.scope.kind == .GLOBAL ||
      context.scope.kind == .STRUCT

    var shouldBeOutsideFunction =
      node.kind == .EXTENSION ||
      node.kind == .FUNCTION ||
      node.kind == .PRECISION ||
      node.kind == .VERSION

    if shouldBeOutsideFunction && !isOutsideFunction {
      context.log.syntaxErrorInsideFunction(node.range)
    } else if !shouldBeOutsideFunction && isOutsideFunction {
      context.log.syntaxErrorOutsideFunction(node.range)
    }
  }

  def parseInclude(context ParserContext, parent Node) bool {
    # See if there is a string literal
    var range = context.current.range
    if !context.expect(.STRING_LITERAL) {
      return true
    }

    # Decode the escapes
    var path string
    try {
      path = dynamic.JSON.parse(range.toString)
    } catch {
      context.log.syntaxErrorInvalidString(range)
      return true
    }

    # Must have access to the file system
    var fileAccess = context.compilationData.fileAccess
    if fileAccess == null {
      context.log.semanticErrorIncludeWithoutFileAccess(range)
      return false
    }

    # Must be able to read the file
    var source = fileAccess(path, range.source.name)
    if source == null {
      context.log.semanticErrorIncludeBadPath(range, path)
      return false
    }

    if source.name in context.processedIncludes {
      # We've already processed this include; no need to do it again
      return true
    }
    context.processedIncludes[source.name] = true

    # Track the included file for jump-to-file in the IDE
    context.includes.append(Include.new(range, source.entireRange))

    # Parse the file and insert it into the parent
    Tokenizer.tokenize(context.log, source, .COMPILE)
    if context.version != source.tokenized.version {
      context.log.syntaxErrorImportWrongVersion(range, path, source)
    }
    var nestedContext = ParserContext.new(context.log, source.tokenized, context.compilationData, context.resolver, context.processedIncludes)
    nestedContext.pushScope(context.scope)
    if !parseStatements(nestedContext, parent, .GLOBAL) || !nestedContext.expect(.END_OF_FILE) {
      return false
    }

    return true
  }

  def parseBlock(context ParserContext) Node {
    var token = context.current
    var block = Node.createBlock
    context.pushScope(Scope.new(.LOCAL, context.scope))
    if !context.expect(.LEFT_BRACE) || !parseStatements(context, block, .LOCAL) || !context.expect(.RIGHT_BRACE) {
      return null
    }
    context.popScope
    return block.withRange(context.spanSince(token.range))
  }

  def isFlag(kind TokenKind) bool {
    switch kind {
      case .LAYOUT, .CONST, .CENTROID, .INVARIANT, .UNIFORM, .ATTRIBUTE, .VARYING, .IN, .OUT, .INOUT, .HIGHP, .MEDIUMP, .LOWP { return true }
      default { return false }
    }
  }

  def skipFlag(context ParserContext) {
    if !context.eat(.LAYOUT) {
      context.next
    } else if context.eat(.LEFT_PARENTHESIS) {
      while !context.peek(.END_OF_FILE) && !context.eat(.RIGHT_PARENTHESIS) {
        context.next
      }
    }
  }

  def parseFlags(context ParserContext, mode VariableKind) SymbolFlags {
    var version300 = context.version == .ES_300
    var flags SymbolFlags = 0

    if mode == .GLOBAL {
      if version300 && context.eat(.LAYOUT) && context.expect(.LEFT_PARENTHESIS) {
        var location = -1
        while true {
          var token = context.current
          if token.kind == .IDENTIFIER && token.range.toString == "location" {
            context.next
            if context.expect(.ASSIGN) {
              if context.peek(.INT_LITERAL) || context.peek(.UINT_LITERAL) {
                location = parseInt(context.current.range.toString)
                context.next
              } else {
                context.expect(.INT_LITERAL)
              }
            }
          } else {
            context.unexpectedToken
            if token.kind != .IDENTIFIER {
              break
            }
            context.next
          }
          if !context.eat(.COMMA) {
            break
          }
        }
        if location != -1 {
          flags |= .HAS_LAYOUT_LOCATION | (location * SymbolFlags.LAYOUT_LOCATION)
        }
        context.expect(.RIGHT_PARENTHESIS)
      }

      else {
        if context.eat(.INVARIANT) {
          flags |= .INVARIANT
        }

        if version300 {
          if context.eat(.FLAT) {
            flags |= .FLAT
          } else if context.eat(.SMOOTH) {
            flags |= .SMOOTH
          }
        }
      }
    }

    if mode != .STRUCT && context.eat(.CONST) {
      flags |= .CONST
    } else if mode == .GLOBAL && context.eat(.UNIFORM) {
      flags |= .UNIFORM
    } else if mode == .GLOBAL && !version300 && context.eat(.ATTRIBUTE) {
      flags |= .ATTRIBUTE
    } else if mode == .GLOBAL && !version300 && context.eat(.VARYING) {
      flags |= .VARYING
    } else if mode == .GLOBAL && version300 && context.eat(.CENTROID) {
      flags |= .CENTROID
      if context.eat(.IN) {
        flags |= .IN
      } else if context.eat(.OUT) {
        flags |= .OUT
      } else {
        context.unexpectedToken
      }
    } else if (mode == .ARGUMENT || version300 && mode == .GLOBAL) && context.eat(.IN) {
      flags |= .IN
    } else if (mode == .ARGUMENT || version300 && mode == .GLOBAL) && context.eat(.OUT) {
      flags |= .OUT
    } else if (mode == .ARGUMENT || version300 && mode == .GLOBAL) && context.eat(.INOUT) {
      flags |= .INOUT
    }

    if context.eat(.HIGHP) {
      flags |= .HIGHP
    } else if context.eat(.MEDIUMP) {
      flags |= .MEDIUMP
    } else if context.eat(.LOWP) {
      flags |= .LOWP
    }

    if isFlag(context.current.kind) {
      context.log.syntaxErrorBadQualifier(context.current.range)
      skipFlag(context)
      while isFlag(context.current.kind) {
        skipFlag(context)
      }
    }

    return flags
  }

  enum ParseTypeMode {
    IGNORE_ERRORS
    REPORT_ERRORS
  }

  def parseType(context ParserContext, mode ParseTypeMode) Node {
    var token = context.current
    var type Type = null

    switch token.kind {
      case .BOOL        { type = .BOOL }
      case .BVEC2       { type = .BVEC2 }
      case .BVEC3       { type = .BVEC3 }
      case .BVEC4       { type = .BVEC4 }
      case .FLOAT       { type = .FLOAT }
      case .INT         { type = .INT }
      case .IVEC2       { type = .IVEC2 }
      case .IVEC3       { type = .IVEC3 }
      case .IVEC4       { type = .IVEC4 }
      case .MAT2        { type = .MAT2 }
      case .MAT3        { type = .MAT3 }
      case .MAT4        { type = .MAT4 }
      case .SAMPLER2D   { type = .SAMPLER2D }
      case .SAMPLERCUBE { type = .SAMPLERCUBE }
      case .VEC2        { type = .VEC2 }
      case .VEC3        { type = .VEC3 }
      case .VEC4        { type = .VEC4 }
      case .VOID        { type = .VOID }

      case .ISAMPLER2D           { type = context.validTypeInVersion300(.ISAMPLER2D) }
      case .ISAMPLER2DARRAY      { type = context.validTypeInVersion300(.ISAMPLER2DARRAY) }
      case .ISAMPLER3D           { type = context.validTypeInVersion300(.ISAMPLER3D) }
      case .ISAMPLERCUBE         { type = context.validTypeInVersion300(.ISAMPLERCUBE) }
      case .MAT2X3               { type = context.validTypeInVersion300(.MAT2X3) }
      case .MAT2X4               { type = context.validTypeInVersion300(.MAT2X4) }
      case .MAT3X2               { type = context.validTypeInVersion300(.MAT3X2) }
      case .MAT3X4               { type = context.validTypeInVersion300(.MAT3X4) }
      case .MAT4X2               { type = context.validTypeInVersion300(.MAT4X2) }
      case .MAT4X3               { type = context.validTypeInVersion300(.MAT4X3) }
      case .SAMPLER2DARRAY       { type = context.validTypeInVersion300(.SAMPLER2DARRAY) }
      case .SAMPLER2DARRAYSHADOW { type = context.validTypeInVersion300(.SAMPLER2DARRAYSHADOW) }
      case .SAMPLER2DSHADOW      { type = context.validTypeInVersion300(.SAMPLER2DSHADOW) }
      case .SAMPLER3D            { type = context.validTypeInVersion300(.SAMPLER3D) }
      case .SAMPLERCUBESHADOW    { type = context.validTypeInVersion300(.SAMPLERCUBESHADOW) }
      case .UINT                 { type = context.validTypeInVersion300(.UINT) }
      case .USAMPLER2D           { type = context.validTypeInVersion300(.USAMPLER2D) }
      case .USAMPLER2DARRAY      { type = context.validTypeInVersion300(.USAMPLER2DARRAY) }
      case .USAMPLER3D           { type = context.validTypeInVersion300(.USAMPLER3D) }
      case .USAMPLERCUBE         { type = context.validTypeInVersion300(.USAMPLERCUBE) }
      case .UVEC2                { type = context.validTypeInVersion300(.UVEC2) }
      case .UVEC3                { type = context.validTypeInVersion300(.UVEC3) }
      case .UVEC4                { type = context.validTypeInVersion300(.UVEC4) }

      case .IDENTIFIER {
        var symbol = context.scope.find(token.range.toString)
        if symbol == null || !symbol.isStruct {
          if mode == .REPORT_ERRORS {
            context.unexpectedToken
          }
          return null
        }
        symbol.useCount++
        type = symbol.resolvedType
      }

      default {
        if mode == .REPORT_ERRORS {
          context.unexpectedToken
        }
        return null
      }
    }

    context.next

    # Parse an optional array size
    if context.version == .ES_300 {
      const arraySize = parseOptionalArraySize(context, true, true)
      if arraySize != null {
        if arraySize == .ERROR {
          type = .ERROR
        } else {
          return Node.createArrayType(type.arrayType(arraySize.value), arraySize.node).withRange(context.spanSince(token.range))
        }
      }
    }

    return Node.createType(type).withRange(context.spanSince(token.range))
  }

  class ArraySize {
    const node Node
    const value int
  }

  namespace ArraySize {
    const ERROR = ArraySize.new(null, -1)
  }

  def parseOptionalArraySize(context ParserContext, allowEmpty bool, allowFull bool) ArraySize {
    if !allowFull {
      parseMultidimensionalArray(context)
      return null
    }

    # Parse an optional array size
    var token = context.current
    if !context.eat(.LEFT_BRACKET) {
      return null
    }

    var node Node
    var value = 0

    # Handle an omitted array size
    if context.eat(.RIGHT_BRACKET) {
      if !allowEmpty {
        context.log.syntaxErrorMissingArraySize(context.spanSince(token.range))
        parseMultidimensionalArray(context)
        return .ERROR
      }

      # Use a placeholder for an omitted array size
      node = Node.createSequence
    }

    else {
      node = context.pratt.parse(context, .LOWEST)
      if node == null || !context.expect(.RIGHT_BRACKET) {
        return .ERROR
      }

      # The array size must be resolved immediately
      context.resolver.resolveNode(node)
      context.resolver.checkConversion(node, .INT)
      if node.resolvedType != .ERROR {
        var folded = Folder.fold(node)
        if folded == null {
          context.log.syntaxErrorConstantRequired(node.range)
        } else if folded.kind == .INT {
          value = folded.asInt
          if value < 1 {
            context.log.syntaxErrorInvalidArraySize(node.range, value)
            value = 0
          }
        }
      }

      # Multidimensional arrays are not supported
      if parseMultidimensionalArray(context) {
        return .ERROR
      }
    }

    return ArraySize.new(node, value)
  }

  def parseMultidimensionalArray(context ParserContext) bool {
    if !context.peek(.LEFT_BRACKET) {
      return false
    }
    while true {
      var token = context.next
      if !context.peek(.RIGHT_BRACKET) && context.pratt.parse(context, .LOWEST) == null || !context.expect(.RIGHT_BRACKET) {
        return true
      }
      context.log.syntaxErrorMultidimensionalArray(context.spanSince(token.range))
      if !context.peek(.LEFT_BRACKET) {
        return true
      }
    }
  }

  def parseFunction(flags SymbolFlags, type Node, name Range, context ParserContext, comments List<string>) Node {
    var originalScope = context.scope
    var function = FunctionSymbol.new(context.compilationData.nextSymbolID, name, name.toString, Scope.new(.FUNCTION, originalScope))
    function.flags |= context.flags | flags | (function.name == "main" ? .EXPORTED_VERTEX | .EXPORTED_FRAGMENT : 0)
    function.comments = comments
    function.returnType = type
    context.pushScope(function.scope)

    # Takes no arguments
    if context.eat(.VOID) {
      if !context.expect(.RIGHT_PARENTHESIS) {
        return null
      }
    }

    # Takes arguments
    else if !context.eat(.RIGHT_PARENTHESIS) {
      while true {
        # Parse leading flags
        var argumentFlags = parseFlags(context, .ARGUMENT)

        # Parse the type
        var argumentType = parseType(context, .REPORT_ERRORS)
        if argumentType == null {
          return null
        }

        # Parse the identifier
        var argumentName = context.current.range
        if !context.expect(.IDENTIFIER) {
          return null
        }

        # Create the argument
        var argument = VariableSymbol.new(context.compilationData.nextSymbolID, argumentName, argumentName.toString, context.scope, .ARGUMENT)
        argument.flags |= argumentFlags
        argument.parsedType = argumentType
        argument.mergedType = argumentType.resolvedType
        function.arguments.append(argument)
        tryToDefineUniquelyInScope(context, argument)
        parseArraySizeAfterSymbol(context, argument)

        # Parse another argument?
        if !context.eat(.COMMA) {
          break
        }
      }

      if !context.expect(.RIGHT_PARENTHESIS) {
        return null
      }
    }

    var previous = originalScope.symbols.get(name.toString, null)
    var hasBlock = !context.eat(.SEMICOLON)

    # Merge adjacent function symbols to support overloading
    if previous == null {
      originalScope.define(function)
    } else if previous.isFunction {
      for link = previous.asFunction; link != null; link = link.previousOverload {
        if !link.hasSameArgumentTypesAs(function) {
          continue
        }

        # Overloading by return type is not allowed
        if link.returnType.resolvedType != function.returnType.resolvedType {
          context.log.syntaxErrorDifferentReturnType(function.returnType.range, function.name,
            function.returnType.resolvedType, link.returnType.resolvedType, link.returnType.range)
        }

        # Defining a function more than once is not allowed
        else if link.block != null || !hasBlock {
          context.log.syntaxErrorDuplicateSymbolDefinition(function.range, link.range)
        }

        # Merge the function with its forward declaration
        else {
          assert(link.sibling == null)
          assert(function.sibling == null)
          link.sibling = function
          function.sibling = link
          function.flags |= link.flags
          link.flags = function.flags
        }
        break
      }

      # Use a singly-linked list to store the function overloads
      function.previousOverload = previous.asFunction
      originalScope.redefine(function)
    } else {
      context.log.syntaxErrorDuplicateSymbolDefinition(name, previous.range)
      return null
    }

    if hasBlock {
      var old = context.flags
      context.flags &= ~(.EXPORTED_VERTEX | .EXPORTED_FRAGMENT | .IMPORTED)
      function.block = parseBlock(context)
      context.flags = old
      if function.block == null {
        return null
      }
    }

    context.popScope
    return Node.createFunction(function).withRange(context.spanSince(type.range))
  }

  def parseArraySizeAfterSymbol(context ParserContext, variable VariableSymbol) {
    const arraySize = parseOptionalArraySize(context, variable.kind != .ARGUMENT, variable.mergedType.isArrayOf == null)
    if arraySize == .ERROR {
      variable.mergedType = .ERROR
    } else if arraySize != null {
      variable.arraySize = arraySize.node
      if variable.mergedType != .ERROR {
        variable.mergedType = variable.mergedType.arrayType(arraySize.value)
      }
    }
  }

  def parseVariables(flags int, type Node, name Range, context ParserContext, comments List<string>) Node {
    var variables = Node.createVariables(context.flags | flags, type)
    while true {
      var symbol = VariableSymbol.new(context.compilationData.nextSymbolID, name, name.toString, context.scope,
        context.scope.kind == .GLOBAL ? .GLOBAL :
        context.scope.kind == .STRUCT ? .STRUCT :
        .LOCAL)
      symbol.flags |= context.flags | flags
      symbol.comments = comments
      symbol.parsedType = type
      parseArraySizeAfterSymbol(context, symbol)

      # Initial value
      var assign = context.current.range
      var value Node
      if context.eat(.ASSIGN) {
        var firstToken = context.current
        value = context.pratt.parse(context, .COMMA)
        if value == null {
          value = Node.createParseError.withRange(context.spanSince(firstToken.range))
        }
      } else {
        assign = null
      }

      var variable = Node.createVariable(symbol, value).withRange(context.spanSince(symbol.range)).withInternalRange(assign)
      symbol.node = variable
      if symbol.isConst {
        # Constants must be resolved immediately
        context.resolver.resolveNode(variable)
      } else {
        # Try to eagerly resolve omitted array sizes
        context.resolver.resolveNode(symbol.parsedType)
        var mergedType = symbol.mergedType
        if mergedType.isArrayOf != null && value != null {
          var typeArraySize = symbol.parsedType.typeArraySize
          var symbolArraySize = symbol.arraySize
          if typeArraySize != null && typeArraySize.isEmptySequence || symbolArraySize != null && symbolArraySize.isEmptySequence {
            context.resolver.resolveNode(value)
            if value.resolvedType.isArrayOf != null && value.resolvedType.arraySize > 0 {
              symbol.mergedType = mergedType.isArrayOf.arrayType(value.resolvedType.arraySize)
            }
          }
        }
      }
      variables.appendChild(variable)
      tryToDefineUniquelyInScope(context, symbol)

      # Are there more variables in this statement?
      if !context.eat(.COMMA) {
        context.expect(.SEMICOLON)
        return variables
      }

      name = context.current.range
      if !context.expect(.IDENTIFIER) {
        return null
      }
    }
  }

  def tryToDefineUniquelyInScope(context ParserContext, symbol Symbol) bool {
    var previous = context.scope.symbols.get(symbol.name, null)
    if previous != null {
      context.log.syntaxErrorDuplicateSymbolDefinition(symbol.range, previous.range)
      return false
    }
    context.scope.define(symbol)
    return true
  }

  def parseStatements(context ParserContext, parent Node, mode VariableKind) bool {
    while !context.peek(.END_OF_FILE) && !context.peek(.RIGHT_BRACE) {
      var includeRange = context.current.range
      if context.eat(.INCLUDE) {
        if mode != .GLOBAL {
          context.log.syntaxErrorIncludeOutsideGlobal(includeRange)
          context.eat(.STRING_LITERAL)
          return false
        }
        if !parseInclude(context, parent) {
          return false
        }
        continue
      }

      var statement = parseStatement(context, mode)
      if statement == null {
        return false
      }

      # Extension blocks are temporary and don't exist in the parsed result
      if statement.kind == .MODIFIER_BLOCK {
        while statement.hasChildren {
          var child = statement.firstChild.remove
          checkStatementLocation(context, child)
          parent.appendChild(child)
        }
      } else {
        checkStatementLocation(context, statement)
        parent.appendChild(statement)
      }
    }

    return true
  }

  class ParseResult {
    const includes List<Include>
  }

  def parse(log Log, tokenized Tokenized, global Node, data CompilerData, scope Scope, resolver Resolver) ParseResult {
    const processedIncludes = StringMap<bool>.new
    var context = ParserContext.new(log, tokenized, data, resolver, processedIncludes)
    context.pushScope(scope)
    if parseStatements(context, global, .GLOBAL) {
      context.expect(.END_OF_FILE)
    }

    return ParseResult.new(context.includes)
  }
}
