namespace GLSLX {
  enum Version {
    ES_100
    ES_300
  }

  enum TokenKind {
    SINGLE_LINE_COMMENT
    MULTI_LINE_COMMENT

    # Standard keywords
    ATTRIBUTE
    BOOL
    BREAK
    BVEC2
    BVEC3
    BVEC4
    CONST
    CONTINUE
    DISCARD
    DO
    ELSE
    FALSE
    FLOAT
    FOR
    HIGHP
    IF
    IN
    INOUT
    INT
    INVARIANT
    IVEC2
    IVEC3
    IVEC4
    LOWP
    MAT2
    MAT3
    MAT4
    MEDIUMP
    OUT
    PRECISION
    RETURN
    SAMPLER2D
    SAMPLERCUBE
    STRUCT
    TRUE
    UNIFORM
    VARYING
    VEC2
    VEC3
    VEC4
    VOID
    WHILE

    # GLSL ES 3.0
    CENTROID
    FLAT
    ISAMPLER2D
    ISAMPLER2DARRAY
    ISAMPLER3D
    ISAMPLERCUBE
    LAYOUT
    MAT2X3
    MAT2X4
    MAT3X2
    MAT3X4
    MAT4X2
    MAT4X3
    SAMPLER2DARRAY
    SAMPLER2DARRAYSHADOW
    SAMPLER2DSHADOW
    SAMPLER3D
    SAMPLERCUBESHADOW
    SMOOTH
    UINT
    USAMPLER2D
    USAMPLER2DARRAY
    USAMPLER3D
    USAMPLERCUBE
    UVEC2
    UVEC3
    UVEC4

    # Non-standard keywords
    DECORATOR
    EXPORT
    EXPORT_FRAGMENT
    EXPORT_VERTEX
    IMPORT

    # Unary
    COMPLEMENT
    DECREMENT
    INCREMENT
    NOT

    # Binary
    BITWISE_AND
    BITWISE_OR
    BITWISE_XOR
    DIVIDE
    EQUAL
    GREATER_THAN
    GREATER_THAN_OR_EQUAL
    LESS_THAN
    LESS_THAN_OR_EQUAL
    LOGICAL_AND
    LOGICAL_OR
    LOGICAL_XOR
    MINUS
    MULTIPLY
    NOT_EQUAL
    PLUS
    REMAINDER
    SHIFT_LEFT
    SHIFT_RIGHT

    # Binary assignment
    ASSIGN
    ASSIGN_ADD
    ASSIGN_BITWISE_AND
    ASSIGN_BITWISE_OR
    ASSIGN_BITWISE_XOR
    ASSIGN_DIVIDE
    ASSIGN_MULTIPLY
    ASSIGN_REMAINDER
    ASSIGN_SHIFT_LEFT
    ASSIGN_SHIFT_RIGHT
    ASSIGN_SUBTRACT

    # Other operators
    COLON
    COMMA
    DOT
    LEFT_BRACE
    LEFT_BRACKET
    LEFT_PARENTHESIS
    QUESTION
    RIGHT_BRACE
    RIGHT_BRACKET
    RIGHT_PARENTHESIS
    SEMICOLON

    # Pragmas
    EXTENSION
    INCLUDE
    PREPROCESSOR_DIRECTIVE
    VERSION

    # Literals
    FLOAT_LITERAL
    IDENTIFIER
    INT_LITERAL
    UINT_LITERAL
    STRING_LITERAL

    # This is always at the end of the token stream
    END_OF_FILE

    def isBinaryOperator bool {
      return self >= TokenKind.BITWISE_AND && self <= TokenKind.ASSIGN_SUBTRACT
    }

    def isIdentifierOrType bool {
      switch self {
        case .IDENTIFIER, .VOID,
          .SAMPLER2D, .SAMPLER2DARRAY, .SAMPLER2DARRAYSHADOW, .SAMPLER2DSHADOW,
          .SAMPLER3D, .SAMPLERCUBE, .SAMPLERCUBESHADOW,
          .ISAMPLER2D, .ISAMPLER2DARRAY, .ISAMPLER3D, .ISAMPLERCUBE,
          .USAMPLER2D, .USAMPLER2DARRAY, .USAMPLER3D, .USAMPLERCUBE,
          .FLOAT, .VEC2, .VEC3, .VEC4,
          .INT, .IVEC2, .IVEC3, .IVEC4,
          .UINT, .UVEC2, .UVEC3, .UVEC4,
          .BOOL, .BVEC2, .BVEC3, .BVEC4,
          .MAT2, .MAT3, .MAT4,
          .MAT2X3, .MAT2X4, .MAT3X2, .MAT3X4, .MAT4X2, .MAT4X3 {
          return true
        }
      }
      return false
    }
  }

  namespace TokenKind {
    def fromKeyword(text string) TokenKind {
      assert(text in Tokenizer.keywords)
      return Tokenizer.keywords[text]
    }
  }

  class Token {
    var range Range
    var kind TokenKind
    var comments List<Range>
  }

  class Tokenized {
    var tokens List<Token>
    var version Version
  }
}

namespace GLSLX.Tokenizer {
  enum TokenPurpose {
    COMPILE
    FORMAT
  }

  def tokenize(log Log, source Source, purpose TokenPurpose) {
    var parts List<string> = (source.contents as dynamic).split(_tokenRegex)
    var tokens List<Token> = []
    var comments List<Range> = null
    var prevCommentTokenCount = 0
    var start = 0

    for i in 0..parts.count {
      var part = parts[i]
      var count = part.count
      var end = start + count
      var range = Range.new(source, start, end)

      if i % 2 != 0 {
        var c = part[0]

        # Identifier
        if c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z' || c == '_' {
          var keyword = keywords.get(part, .END_OF_FILE)
          if keyword != .END_OF_FILE {
            tokens.append(Token.new(range, keyword, comments))
          } else if part in reservedWords {
            log.syntaxErrorReservedWord(range)
          } else {
            tokens.append(Token.new(range, .IDENTIFIER, comments))
          }
        }

        # Decorator
        else if c == '@' {
          var kind TokenKind = .DECORATOR
          switch part {
            case "@vertex" { kind = .EXPORT_VERTEX }
            case "@fragment" { kind = .EXPORT_FRAGMENT }
          }
          tokens.append(Token.new(range, kind, comments))
        }

        # Number
        else if c >= '0' && c <= '9' || c == '.' && count > 1 {
          if _intRegex.test(part) {
            c = part[count - 1]
            tokens.append(Token.new(range, c == 'u' || c == 'U' ? .UINT_LITERAL : .INT_LITERAL, comments))
          } else {
            tokens.append(Token.new(range, .FLOAT_LITERAL, comments))
          }
        }

        # Pragma
        else if c == '#' {
          var kind = TokenKind.PREPROCESSOR_DIRECTIVE
          var j = 1
          while j < part.count && (part[j] == ' ' || part[j] == '\t') {
            j += 1
          }
          switch part.slice(j) {
            case "extension" { kind = .EXTENSION }
            case "include" { kind = .INCLUDE }
            case "version" { kind = .VERSION }
          }
          tokens.append(Token.new(range, kind, comments))
        }

        # String literal
        else if c == '"' {
          tokens.append(Token.new(range, .STRING_LITERAL, comments))
        }

        # Operator
        else {
          var kind = operators.get(part, .END_OF_FILE)
          if kind == .END_OF_FILE {
            if part.startsWith("//") {
              if purpose == .FORMAT {
                kind = .SINGLE_LINE_COMMENT
              } else {
                (comments ?= []).append(range)
              }
            } else if part.startsWith("/*") {
              if purpose == .FORMAT {
                kind = .MULTI_LINE_COMMENT
              } else {
                (comments ?= []).append(range)
              }
            }
          }
          if kind != .END_OF_FILE {
            tokens.append(Token.new(range, kind, comments))
          }
        }
      }

      else if part != "" {
        log.syntaxErrorExtraData(range, part)
        break
      }

      # Reset the comment list after every non-comment token
      if tokens.count != prevCommentTokenCount {
        comments = null
        prevCommentTokenCount = tokens.count
      }

      start = end
    }

    var version Version = .ES_100
    if tokens.count > 2 {
      var t0 = tokens[0]
      var t1 = tokens[1]
      var t2 = tokens[2]
      if t0.kind == .VERSION && t1.kind == .INT_LITERAL && t2.kind == .IDENTIFIER && t1.range.toString == "300" && t2.range.toString == "es" {
        version = .ES_300
      }
    }

    tokens.append(Token.new(Range.new(source, start, start), .END_OF_FILE, comments))
    source.tokenized = Tokenized.new(tokens, version)
  }

  # The order matters here due to greedy matching
  const _tokenRegex = dynamic.RegExp.new(
    "(" +

    # Float literal
    "\\.[0-9]+[eE][+-]?[0-9]+\\b|" + # Floating-point constant
    "\\.[0-9]+\\b|" + # Floating-point constant
    "[0-9]+\\.[0-9]+[eE][+-]?[0-9]+\\b|" + # Floating-point constant
    "[0-9]+\\.[0-9]+\\b|" + # Floating-point constant
    "[0-9]+\\.[eE][+-]?[0-9]+\\b|" + # Floating-point constant
    "[0-9]+\\.|" + # Floating-point constant
    "[0-9]+[eE][+-]?[0-9]+\\b|" + # Floating-point constant

    # Int literals
    "[1-9][0-9]*[uU]?\\b|" + # Decimal int literal
    "0[0-7]*[uU]?\\b|" + # Octal int literal
    "0[xX][0-9A-Fa-f]+[uU]?\\b|" + # Hexadecimal int literal

    # Other
    "[ \t\r\n]|" + # Whitespace
    "/\\*(?:.|\r\n|\n)*?\\*/|" + # Multi-line comment
    "//.*|" + # Single-line comment
    "&&|\\|\\||\\^\\^|\\+\\+|--|<<=?|>>=?|[()[\\]{}\\.,?:;]|[+\\-*/%=!<>&|^~]=?|" + # Operator
    "@?[A-Za-z_][A-Za-z0-9_]*\\b|" + # Identifier
    "#\\s*\\w+\\b|" + # Preprocessor directive
    "\"(?:[^\"\\n\\\\]|\\\\.)*\"?" + # String literal

    ")"
  )

  const _intRegex = dynamic.RegExp.new(
    "^(" +
    "[1-9][0-9]*|" +
    "0[0-7]*|" +
    "0[xX][0-9A-Fa-f]+" +
    ")[uU]?$"
  )

  const keywords StringMap<TokenKind> = {
    # Standard keywords
    "attribute": .ATTRIBUTE,
    "bool": .BOOL,
    "break": .BREAK,
    "bvec2": .BVEC2,
    "bvec3": .BVEC3,
    "bvec4": .BVEC4,
    "const": .CONST,
    "continue": .CONTINUE,
    "discard": .DISCARD,
    "do": .DO,
    "else": .ELSE,
    "false": .FALSE,
    "float": .FLOAT,
    "for": .FOR,
    "highp": .HIGHP,
    "if": .IF,
    "in": .IN,
    "inout": .INOUT,
    "int": .INT,
    "invariant": .INVARIANT,
    "ivec2": .IVEC2,
    "ivec3": .IVEC3,
    "ivec4": .IVEC4,
    "lowp": .LOWP,
    "mat2": .MAT2,
    "mat3": .MAT3,
    "mat4": .MAT4,
    "mediump": .MEDIUMP,
    "out": .OUT,
    "precision": .PRECISION,
    "return": .RETURN,
    "sampler2D": .SAMPLER2D,
    "samplerCube": .SAMPLERCUBE,
    "struct": .STRUCT,
    "true": .TRUE,
    "uniform": .UNIFORM,
    "varying": .VARYING,
    "vec2": .VEC2,
    "vec3": .VEC3,
    "vec4": .VEC4,
    "void": .VOID,
    "while": .WHILE,

    # GLSL ES 3.0
    "centroid": .CENTROID,
    "flat": .FLAT,
    "isampler2D": .ISAMPLER2D,
    "isampler2DArray": .ISAMPLER2DARRAY,
    "isampler3D": .ISAMPLER3D,
    "isamplerCube": .ISAMPLERCUBE,
    "layout": .LAYOUT,
    "mat2x2": .MAT2,
    "mat2x3": .MAT2X3,
    "mat2x4": .MAT2X4,
    "mat3x2": .MAT3X2,
    "mat3x3": .MAT3,
    "mat3x4": .MAT3X4,
    "mat4x2": .MAT4X2,
    "mat4x3": .MAT4X3,
    "mat4x4": .MAT4,
    "sampler2DArray": .SAMPLER2DARRAY,
    "sampler2DArrayShadow": .SAMPLER2DARRAYSHADOW,
    "sampler2DShadow": .SAMPLER2DSHADOW,
    "sampler3D": .SAMPLER3D,
    "samplerCubeShadow": .SAMPLERCUBESHADOW,
    "smooth": .SMOOTH,
    "uint": .UINT,
    "usampler2D": .USAMPLER2D,
    "usampler2DArray": .USAMPLER2DARRAY,
    "usampler3D": .USAMPLER3D,
    "usamplerCube": .USAMPLERCUBE,
    "uvec2": .UVEC2,
    "uvec3": .UVEC3,
    "uvec4": .UVEC4,

    # Non-standard keywords
    "export": .EXPORT,
    "import": .IMPORT,
  }

  const operators StringMap<TokenKind> = {
    # Unary
    "~": .COMPLEMENT,
    "--": .DECREMENT,
    "++": .INCREMENT,
    "!": .NOT,

    # Binary
    "&": .BITWISE_AND,
    "|": .BITWISE_OR,
    "^": .BITWISE_XOR,
    "/": .DIVIDE,
    "==": .EQUAL,
    ">": .GREATER_THAN,
    ">=": .GREATER_THAN_OR_EQUAL,
    "<": .LESS_THAN,
    "<=": .LESS_THAN_OR_EQUAL,
    "&&": .LOGICAL_AND,
    "||": .LOGICAL_OR,
    "^^": .LOGICAL_XOR,
    "-": .MINUS,
    "*": .MULTIPLY,
    "!=": .NOT_EQUAL,
    "+": .PLUS,
    "%": .REMAINDER,
    "<<": .SHIFT_LEFT,
    ">>": .SHIFT_RIGHT,

    # Binary assignment
    "=": .ASSIGN,
    "+=": .ASSIGN_ADD,
    "&=": .ASSIGN_BITWISE_AND,
    "|=": .ASSIGN_BITWISE_OR,
    "^=": .ASSIGN_BITWISE_XOR,
    "/=": .ASSIGN_DIVIDE,
    "*=": .ASSIGN_MULTIPLY,
    "%=": .ASSIGN_REMAINDER,
    "<<=": .ASSIGN_SHIFT_LEFT,
    ">>=": .ASSIGN_SHIFT_RIGHT,
    "-=": .ASSIGN_SUBTRACT,

    # Other
    ":": .COLON,
    ",": .COMMA,
    ".": .DOT,
    "{": .LEFT_BRACE,
    "[": .LEFT_BRACKET,
    "(": .LEFT_PARENTHESIS,
    "?": .QUESTION,
    "}": .RIGHT_BRACE,
    "]": .RIGHT_BRACKET,
    ")": .RIGHT_PARENTHESIS,
    ";": .SEMICOLON,
  }

  const reservedWords = {
    "asm": 0,
    "cast": 0,
    "class": 0,
    "default": 0,
    "double": 0,
    "dvec2": 0,
    "dvec3": 0,
    "dvec4": 0,
    "enum": 0,
    "extern": 0,
    "external": 0,
    "fixed": 0,
    "fvec2": 0,
    "fvec3": 0,
    "fvec4": 0,
    "goto": 0,
    "half": 0,
    "hvec2": 0,
    "hvec3": 0,
    "hvec4": 0,
    "inline": 0,
    "input": 0,
    "interface": 0,
    "long": 0,
    "namespace": 0,
    "noinline": 0,
    "output": 0,
    "packed": 0,
    "public": 0,
    "sampler1D": 0,
    "sampler1DShadow": 0,
    "sampler2DRect": 0,
    "sampler2DRectShadow": 0,
    "sampler3DRect": 0,
    "short": 0,
    "sizeof": 0,
    "static": 0,
    "superp": 0,
    "switch": 0,
    "template": 0,
    "this": 0,
    "typedef": 0,
    "union": 0,
    "unsigned": 0,
    "using": 0,
    "volatile": 0,
  }
}
