namespace GLSLX {
  const ARRAY_COUNT_OMITTED = -1
  const ARRAY_COUNT_UNKNOWN = -2

  class Type {
    const symbol Symbol
    const isArrayOf Type
    const arrayCount int
    var containsArray = false
    var containsSampler = false
    var _arrayTypes IntMap<Type> = null

    def rootType Type {
      if isArrayOf != null {
        return isArrayOf.rootType
      }
      return self
    }

    # A count of "0" means an array with an unknown size
    def arrayType(count int) Type {
      assert(count > 0 || count == ARRAY_COUNT_OMITTED || count == ARRAY_COUNT_UNKNOWN)
      assert(isArrayOf == null)
      _arrayTypes ?= {}
      var arrayType = _arrayTypes.get(count, null)
      if arrayType == null {
        _arrayTypes[count] = arrayType = Type.new(null, self, count)
        arrayType.containsArray = true
        arrayType.containsSampler = containsSampler
      }
      return arrayType
    }

    def toString string {
      if isArrayOf != null {
        return arrayCount > 0 ? "\(isArrayOf)[\(arrayCount)]" : "\(isArrayOf)[]"
      }
      return symbol.name
    }

    # For index expressions where "0 <= index < indexCount" (so indexCount == 0 means this type is un-indexable)
    def indexCount int {
      switch self {
        case BVEC2, VEC2, IVEC2, UVEC2, MAT2, MAT2X3, MAT2X4 { return 2 }
        case BVEC3, VEC3, IVEC3, UVEC3, MAT3, MAT3X2, MAT3X4 { return 3 }
        case BVEC4, VEC4, IVEC4, UVEC4, MAT4, MAT4X2, MAT4X3 { return 4 }
        default { return arrayCount }
      }
    }

    # For index expressions
    def indexType Type {
      switch self {
        case BVEC2, BVEC3, BVEC4 { return BOOL }
        case VEC2, VEC3, VEC4 { return FLOAT }
        case IVEC2, IVEC3, IVEC4 { return INT }
        case UVEC2, UVEC3, UVEC4 { return UINT }
        case MAT2, MAT3X2, MAT4X2 { return VEC2 }
        case MAT3, MAT2X3, MAT4X3 { return VEC3 }
        case MAT4, MAT2X4, MAT3X4 { return VEC4 }
        default { return isArrayOf }
      }
    }

    # For constructor expressions, returns the number of required elements
    def componentCount int {
      switch self {
        case BOOL, FLOAT, INT, UINT { return 1 }
        case BVEC2, VEC2, IVEC2, UVEC2 { return 2 }
        case BVEC3, VEC3, IVEC3, UVEC3 { return 3 }
        case BVEC4, VEC4, IVEC4, UVEC4, MAT2 { return 4 }
        case MAT2X3, MAT3X2 { return 6 }
        case MAT2X4, MAT4X2 { return 8 }
        case MAT3 { return 9 }
        case MAT3X4, MAT4X3 { return 12 }
        case MAT4 { return 16 }
        default { return 0 }
      }
    }

    # For constructor expressions, returns the base element type corresponding to componentCount
    def componentType Type {
      switch self {
        case BOOL, BVEC2, BVEC3, BVEC4 { return BOOL }
        case FLOAT, VEC2, VEC3, VEC4, MAT2, MAT3, MAT4, MAT2X3, MAT2X4, MAT3X2, MAT3X4, MAT4X2, MAT4X3 { return FLOAT }
        case INT, IVEC2, IVEC3, IVEC4 { return INT }
        case UINT, UVEC2, UVEC3, UVEC4 { return UINT }
        default { return null }
      }
    }

    # Vector types are the only ones with swizzles
    def isVector bool {
      switch self {
        case BVEC2, BVEC3, BVEC4, IVEC2, IVEC3, IVEC4, UVEC2, UVEC3, UVEC4, VEC2, VEC3, VEC4 { return true }
        default { return false }
      }
    }

    def isMatrix bool {
      switch self {
        case MAT2, MAT3, MAT4, MAT2X3, MAT2X4, MAT3X2, MAT3X4, MAT4X2, MAT4X3 { return true }
        default { return false }
      }
    }

    def hasIntComponents bool {
      return componentType == .INT
    }

    def hasUintComponents bool {
      return componentType == .UINT
    }

    def hasFloatComponents bool {
      return componentType == .FLOAT
    }

    def hasIntOrUintComponents bool {
      var type = componentType
      return type == .INT || type == .UINT
    }

    def hasFloatOrIntOrUintComponents bool {
      var type = componentType
      return type == .FLOAT || type == .INT || type == .UINT
    }

    def canUseEqualityOperators(version Version) bool {
      return !containsSampler && (!containsArray || version == .ES_300)
    }

    def isVoidOrContainsArray bool {
      # The sequence operator "," cannot necessarily be used with void. The
      # standard says "Support for the void type with the sequence operator
      # is not mandated in GLSL ES 3.0". Furthermore the GLSL compiler in
      # Chrome and Firefox for WebGL 2 also strangely forbids this for both
      # arrays and structs containing arrays.
      return self == .VOID || containsArray
    }

    def _setContainsSampler Type {
      containsSampler = true
      return self
    }
  }

  namespace Type {
    const BOOL = StructSymbol.new(-1, null, "bool", null).resolvedType
    const BVEC2 = StructSymbol.new(-2, null, "bvec2", null).resolvedType
    const BVEC3 = StructSymbol.new(-3, null, "bvec3", null).resolvedType
    const BVEC4 = StructSymbol.new(-4, null, "bvec4", null).resolvedType
    const ERROR = StructSymbol.new(-5, null, "<error>", null).resolvedType
    const FLOAT = StructSymbol.new(-6, null, "float", null).resolvedType
    const INT = StructSymbol.new(-7, null, "int", null).resolvedType
    const IVEC2 = StructSymbol.new(-8, null, "ivec2", null).resolvedType
    const IVEC3 = StructSymbol.new(-9, null, "ivec3", null).resolvedType
    const IVEC4 = StructSymbol.new(-10, null, "ivec4", null).resolvedType
    const MAT2 = StructSymbol.new(-11, null, "mat2", null).resolvedType
    const MAT3 = StructSymbol.new(-12, null, "mat3", null).resolvedType
    const MAT4 = StructSymbol.new(-13, null, "mat4", null).resolvedType
    const SAMPLER2D = StructSymbol.new(-14, null, "sampler2D", null).resolvedType._setContainsSampler
    const SAMPLERCUBE = StructSymbol.new(-15, null, "samplerCube", null).resolvedType._setContainsSampler
    const VEC2 = StructSymbol.new(-16, null, "vec2", null).resolvedType
    const VEC3 = StructSymbol.new(-17, null, "vec3", null).resolvedType
    const VEC4 = StructSymbol.new(-18, null, "vec4", null).resolvedType
    const VOID = StructSymbol.new(-19, null, "void", null).resolvedType

    # GLSL ES 3.0
    const ISAMPLER2D = StructSymbol.new(-20, null, "isampler2D", null).resolvedType._setContainsSampler
    const ISAMPLER2DARRAY = StructSymbol.new(-21, null, "isampler2DArray", null).resolvedType._setContainsSampler
    const ISAMPLER3D = StructSymbol.new(-22, null, "isampler3D", null).resolvedType._setContainsSampler
    const ISAMPLERCUBE = StructSymbol.new(-23, null, "isamplerCube", null).resolvedType._setContainsSampler
    const MAT2X3 = StructSymbol.new(-24, null, "mat2x3", null).resolvedType
    const MAT2X4 = StructSymbol.new(-25, null, "mat2x4", null).resolvedType
    const MAT3X2 = StructSymbol.new(-26, null, "mat3x2", null).resolvedType
    const MAT3X4 = StructSymbol.new(-27, null, "mat3x4", null).resolvedType
    const MAT4X2 = StructSymbol.new(-28, null, "mat4x2", null).resolvedType
    const MAT4X3 = StructSymbol.new(-29, null, "mat4x3", null).resolvedType
    const SAMPLER2DARRAY = StructSymbol.new(-30, null, "sampler2DArray", null).resolvedType._setContainsSampler
    const SAMPLER2DARRAYSHADOW = StructSymbol.new(-31, null, "sampler2DArrayShadow", null).resolvedType._setContainsSampler
    const SAMPLER2DSHADOW = StructSymbol.new(-32, null, "sampler2DShadow", null).resolvedType._setContainsSampler
    const SAMPLER3D = StructSymbol.new(-33, null, "sampler3D", null).resolvedType._setContainsSampler
    const SAMPLERCUBESHADOW = StructSymbol.new(-34, null, "samplerCubeShadow", null).resolvedType._setContainsSampler
    const UINT = StructSymbol.new(-35, null, "uint", null).resolvedType
    const USAMPLER2D = StructSymbol.new(-36, null, "usampler2D", null).resolvedType._setContainsSampler
    const USAMPLER2DARRAY = StructSymbol.new(-37, null, "usampler2DArray", null).resolvedType._setContainsSampler
    const USAMPLER3D = StructSymbol.new(-38, null, "usampler3D", null).resolvedType._setContainsSampler
    const USAMPLERCUBE = StructSymbol.new(-39, null, "usamplerCube", null).resolvedType._setContainsSampler
    const UVEC2 = StructSymbol.new(-40, null, "uvec2", null).resolvedType
    const UVEC3 = StructSymbol.new(-41, null, "uvec3", null).resolvedType
    const UVEC4 = StructSymbol.new(-42, null, "uvec4", null).resolvedType

    const BUILT_INS = [
      BOOL,
      BVEC2,
      BVEC3,
      BVEC4,
      FLOAT,
      INT,
      IVEC2,
      IVEC3,
      IVEC4,
      MAT2,
      MAT3,
      MAT4,
      SAMPLER2D,
      SAMPLERCUBE,
      VEC2,
      VEC3,
      VEC4,
    ]

    # GLSL ES 3.0
    const BUILT_INS_300 = [
      ISAMPLER2D,
      ISAMPLER2DARRAY,
      ISAMPLER3D,
      ISAMPLERCUBE,
      MAT2X3,
      MAT2X4,
      MAT3X2,
      MAT3X4,
      MAT4X2,
      MAT4X3,
      SAMPLER2DARRAY,
      SAMPLER2DARRAYSHADOW,
      SAMPLER2DSHADOW,
      SAMPLERCUBESHADOW,
      UINT,
      USAMPLER2D,
      USAMPLER2DARRAY,
      USAMPLER3D,
      USAMPLERCUBE,
      UVEC2,
      UVEC3,
      UVEC4,
    ]

    def matrixOrVectorType(cols int, rows int) Type {
      switch cols * 10 + rows {
        case 21, 12 { return .VEC2 }
        case 31, 13 { return .VEC3 }
        case 41, 14 { return .VEC4 }
        case 22 { return .MAT2 }
        case 23 { return .MAT2X3 }
        case 24 { return .MAT2X4 }
        case 32 { return .MAT3X2 }
        case 33 { return .MAT3 }
        case 34 { return .MAT3X4 }
        case 42 { return .MAT4X2 }
        case 43 { return .MAT4X3 }
        case 44 { return .MAT4 }
        default { return null }
      }
    }
  }
}
